# Generated by Django 4.2.1 on 2023-10-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dune', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dune',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='dune',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='dune',
            index=models.Index(fields=['-time_create'], name='dune_dune_time_cr_0bcdf7_idx'),
        ),
    ]
