# Generated by Django 4.2.1 on 2023-10-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dune', '0003_alter_dune_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dune',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
