# Generated by Django 4.2.1 on 2023-12-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dune', '0009_rename_affiliation_planet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dune',
            name='planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='dune.planet'),
        ),
    ]
