# Generated by Django 4.2.1 on 2023-12-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dune', '0011_tagpost_author_tagpost_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='count_satellites',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
